manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: nanopb
      url-base: https://github.com/nanopb
    - name: private
      url-base: https://github.com/seasea128
  projects:
    - name: zephyr
      remote: private
      revision: rtc_fix
      # revision: main
      import:
        name-allowlist:
          - cmsis
          - hal_stm32
          - fatfs
    - name: nanopb
      remote: nanopb
      revision: 0.4.9.1
      # revision: 7307ce399b81ddcb3c3a5dc862c52d4754328d38
      path: modules/lib/nanopb
    - name: Protobuf-FYP
      remote: private
      path: MasterController/Protobuf-FYP
  self:
    path: MasterController
