manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: nanopb
      url-base: https://github.com/nanopb
    - name: private
      url-base: https://github.com/seasea128
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: ee250a11ce503fdf24793afac0712bacd26759da
      import: 
        name-allowlist:
          - cmsis
          - hal_stm32
          - fatfs
    - name: nanopb
      remote: nanopb
      revision: 7307ce399b81ddcb3c3a5dc862c52d4754328d38
      path: modules/lib/nanopb
    - name: Protobuf-FYP
      remote: private
      path: MasterController/Protobuf-FYP
  self:
    path: MasterController
  
